openapi: 3.0.1
info:
  title: Product iiiii
  description: product services
  version: "2.0"
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /deletestudent:
    delete:
      tags:
      - student-controller
      operationId: deleteStudent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /swagger-resources/configuration/security:
    get:
      tags:
      - api-resource-controller
      operationId: securityConfiguration
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityConfiguration'
  /updatestudent:
    put:
      tags:
      - student-controller
      operationId: updateStudet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /info:
    get:
      tags:
      - student-controller
      operationId: info
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /swagger-resources:
    get:
      tags:
      - api-resource-controller
      operationId: swaggerResources
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SwaggerResource'
  /readstudents:
    get:
      tags:
      - student-controller
      operationId: readStudents
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
  /swagger-resources/configuration/ui:
    get:
      tags:
      - api-resource-controller
      operationId: uiConfiguration
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UiConfiguration'
  /v3/api-docs:
    get:
      tags:
      - open-api-controller-web-mvc
      operationId: getDocumentation
      parameters:
      - name: group
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
            application/hal+json:
              schema:
                type: string
  /createstudent:
    post:
      tags:
      - student-controller
      operationId: createStudent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /v2/api-docs:
    get:
      tags:
      - swagger-2-controller-web-mvc
      operationId: getDocumentation_1
      parameters:
      - name: group
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
            application/hal+json:
              schema:
                type: string
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        email:
          type: string
    SecurityConfiguration:
      type: object
      properties:
        apiKey:
          type: string
        apiKeyVehicle:
          type: string
        apiKeyName:
          type: string
        clientId:
          type: string
        clientSecret:
          type: string
        realm:
          type: string
        appName:
          type: string
        scopeSeparator:
          type: string
        additionalQueryStringParams:
          type: object
          additionalProperties:
            type: object
        useBasicAuthenticationWithAccessCodeGrant:
          type: boolean
        enableCsrfSupport:
          type: boolean
    SwaggerResource:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
        swaggerVersion:
          type: string
        location:
          type: string
    UiConfiguration:
      type: object
      properties:
        deepLinking:
          type: boolean
        displayOperationId:
          type: boolean
        defaultModelsExpandDepth:
          type: integer
          format: int32
        defaultModelExpandDepth:
          type: integer
          format: int32
        defaultModelRendering:
          type: string
          enum:
          - EXAMPLE
          - MODEL
        displayRequestDuration:
          type: boolean
        docExpansion:
          type: string
          enum:
          - NONE
          - LIST
          - FULL
        filter:
          type: object
        maxDisplayedTags:
          type: integer
          format: int32
        operationsSorter:
          type: string
          enum:
          - ALPHA
          - METHOD
        showExtensions:
          type: boolean
        showCommonExtensions:
          type: boolean
        tagsSorter:
          type: string
          enum:
          - ALPHA
        validatorUrl:
          type: string
        supportedSubmitMethods:
          type: array
          items:
            type: string
        swaggerBaseUiUrl:
          type: string
